apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: istio-system
spec:
  acme:
    # For staging: https://acme-staging-v02.api.letsencrypt.org/directory
    server: https://acme-v02.api.letsencrypt.org/directory 
    email: wuhanstudio@qq.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}
      http01:
        ingress:
          class: istio
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: https-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https-app
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: app-wuhanstudio-uk-tls
      hosts:
        - 'app.wuhanstudio.uk'
    - port:
        number: 443
        name: https-grafana
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: grafana-wuhanstudio-uk-tls
      hosts:
        - 'grafana.wuhanstudio.uk'
    - port:
        number: 443
        name: https-jaeger
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: jaeger-wuhanstudio-uk-tls
      hosts:
        - 'jaeger.wuhanstudio.uk'
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: app-wuhanstudio-uk
  namespace: istio-system
spec:
  secretName: app-wuhanstudio-uk-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: app.wuhanstudio.uk
  dnsNames:
  - app.wuhanstudio.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: jaeger-wuhanstudio-uk
  namespace: istio-system
spec:
  secretName: jaeger-wuhanstudio-uk-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: jaeger.wuhanstudio.uk
  dnsNames:
  - jaeger.wuhanstudio.uk
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-wuhanstudio-uk
  namespace: istio-system
spec:
  secretName: grafana-wuhanstudio-uk-tls
  issuerRef:
    name: letsencrypt-prod
  commonName: grafana.wuhanstudio.uk
  dnsNames:
  - grafana.wuhanstudio.uk
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: fleetman-webapps
spec:
  hosts:
    - app.wuhanstudio.uk
  gateways:
    - https-gateway
  http:
    - route:
      - destination:
          host: fleetman-webapp
          port:
            number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: jaeger-webapps
  namespace: istio-system
spec:
  hosts:
    - jaeger.wuhanstudio.uk
  gateways:
    - default/https-gateway
  http:
    - route:
      - destination:
          host: tracing
          port:
            number: 80
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grafana-webapps
  namespace: istio-system
spec:
  hosts:
    - "grafana.wuhanstudio.uk"
  gateways:
    - default/https-gateway
  http:
    - route:
      - destination:
          host: grafana
          port:
            number: 3000